In [1]:
import re
import requests
import pandas as pd
import urllib
import os
from urllib.request import urlopen
import time

In [ ]:
paper_df = pd.read_csv('ms_paper2.csv', 
                         sep=';', 
                         on_bad_lines='skip')
paper_df = paper_df.reset_index()
site_df = pd.read_csv('ms_site2.csv', 
                         sep=';', 
                         on_bad_lines='skip')
site_df = site_df.reset_index()

In [ ]:
paper_df

In [ ]:
site_df

In [25]:
paper_df = df.drop(['FAU', 'AD'], axis=1)
paper_df.to_csv('ms_paper.csv', sep=';')

In [3]:
df = df[['PMID','FAU', 'AD']]
df['FAU'] = df['FAU'].astype(("string"))
df['AD'] = df['AD'].astype(("string"))
df['FAU'].fillna('', inplace=True)
df['AD'].fillna('', inplace=True)

In [4]:
df['FAU'] = df['FAU'].apply(lambda x: x.split('/'))
df['AD'] = df['AD'].apply(lambda x: x.split('/'))

In [5]:
df

,PMID,FAU,AD
0,30300457,"[Dobson, R , Giovannoni, G]","[Preventive Neurology Unit, Wolfson Institute ..."
1,29791948,"[Yamout, Bassem I , Alroughani, Raed]",[Department of Neurology-Nehmeh and Therese To...
2,25887774,"[Katz Sand, Ilana]","[Department of Neurology, Corinne Goldsmith Di..."
3,27956442,"[Doshi, Anisha , Chataway, Jeremy]","[University College London, London, UK anisha...."
4,27794524,"[Correale, Jorge , Gaitán, María I , Ysrrael...",[]
...,...,...,...
9985,36402726,"[Silveira, Stephanie L , Motl, Robert W , Ma...","[Department of Kinesiology, Health Promotion, ..."
9986,36793718,"[Liu, Pan , Yan, Hui , Li, Haizhe , Zhang, ...","[Department of Neurology, The Central Hospital..."
9987,36058956,"[Zali, Alireza , Motavaf, Mahsa , Safari, Sa...","[Functional Neurosurgery Research Center, Shoh..."
9988,17492609,"[Alarcia-Alejos, R , Ara-Callizo, J R , Mart...","[Servicio de Neurología, Hospital Universitari..."
9989,35716475,"[Serrazina, Filipa , Salavisa, Manuel , Corr...","[Neurology Department, Hospital de Egas Moniz,..."

In [6]:
rows = []
for _, row in df.iterrows():
    for i in range(max(len(row['FAU']), len(row['AD']))):
        person = row['FAU'][i] if i < len(row['FAU']) else None
        site = row['AD'][i] if i < len(row['AD']) else None
        rows.append({'PMID': row['PMID'], 'FAU': person, 'AD': site})

# Creating a new DataFrame
new_df = pd.DataFrame(rows)


new_df

,PMID,FAU,AD
0,30300457,"Dobson, R","Preventive Neurology Unit, Wolfson Institute o..."
1,30300457,"Giovannoni, G","Royal London Hospital, London, UK."
2,30300457,None,"Royal London Hospital, London, UK."
3,30300457,None,"Blizard Institute, London, UK."
4,29791948,"Yamout, Bassem I",Department of Neurology-Nehmeh and Therese Toh...
...,...,...,...
43599,17492609,"Martín-Martínez, J",None
43600,17492609,"García-Gomara, M J",None
43601,35716475,"Serrazina, Filipa","Neurology Department, Hospital de Egas Moniz, ..."
43602,35716475,"Salavisa, Manuel","Neurology Department, Hospital de Egas Moniz,..."
43603,35716475,"Correia, Ana Sofia","Neurology Department, Hospital de Egas Moniz,..."

In [ ]:
result_df.to_csv('ms_site.csv', sep=';')

In [1]:
b[f"{random.choice(range(1, 9))} + {random.choice(range(1, 9))} = "] = 5

NameError: name 'c' is not defined